POST http://localhost:2525/imposters
Content-Type: application/json

{
   "name":"ex1",
   "port":4001,
   "protocol":"http",
   "stubs":[
      {
         "responses":[
            {
               "is":{
                  "statusCode":400,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "error":"Idade mínima não atingida"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/alunos",
                  "method":"POST"
               }
            },
            {
               "equals":{
                  "body":{
                     "idade":9
                  }
               }
            }
         ]
      },
      {
         "responses":[
            {
               "is":{
                  "statusCode":404,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "error":"curso não encontrado"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/alunos",
                  "method":"POST"
               }
            },
            {
               "contains":{
                  "body":{
                     "curso":"invalido"
                  }
               }
            }
         ]
      },
      {
         "responses":[
            {
               "is":{
                  "statusCode":201,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "mensagem":"aluno adicionado",
                     "id":3
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/alunos",
                  "method":"POST"
               }
            }
         ]
      },
      {
         "responses":[
            {
               "is":{
                  "statusCode":200,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":[
                     {
                        "id":1,
                        "nome":"laranja",
                        "idade":13,
                        "curso":"design"
                     },
                     {
                        "id":2,
                        "nome":"esparguete",
                        "idade":16,
                        "curso":"multimédia"
                     }
                  ]
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/alunos",
                  "method":"GET"
               }
            }
         ]
      },
      {
         "responses":[
            {
               "is":{
                  "statusCode":200,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "id":1,
                     "nome":"laranja",
                     "idade":13,
                     "curso":"design"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/alunos/1",
                  "method":"GET"
               }
            }
         ]
      },
      {
         "responses":[
            {
               "is":{
                  "statusCode":200,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "mensagem":"aluno 1 atualizado"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/alunos/1",
                  "method":"PUT"
               }
            }
         ]
      },
      {
         "responses":[
            {
               "is":{
                  "statusCode":404,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "erro":"aluno não existe"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/alunos/2",
                  "method":"PUT"
               }
            }
         ]
      },
      {
         "responses":[
            {
               "is":{
                  "statusCode":200,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "mensagem":"aluno removido com sucesso"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "path":"/api/alunos/1",
                  "method":"DELETE",
                  "headers":{
                     "cargo":"Admin"
                  }
               }
            }
         ]
      },
      {
         "responses":[
            {
               "is":{
                  "statusCode":403,
                  "headers":{
                     "Content-Type":"application/json"
                  },
                  "body":{
                     "erro":"Acesso negado, apenas administradores"
                  }
               }
            }
         ],
         "predicates":[
            {
               "equals":{
                  "method":"DELETE"
               }
            }
         ]
      }
   ]
}


###
GET http://localhost:4001/api/alunos
Content-Type: application/json

###
GET http://localhost:4001/api/alunos/1
Content-Type: application/json


###
POST http://localhost:4001/api/alunos
Content-Type: application/json

{
  "nome": "Francisca",
  "idade": 17,
  "curso": "design"
}

###
POST http://localhost:4001/api/alunos
Content-Type: application/json

{
  "nome": "Rodrigo",
  "idade": 15,
  "curso": "invalido"
}

###
POST http://localhost:4001/api/alunos
Content-Type: application/json

{
  "nome": "Marta",
  "idade": 9,
  "curso": "informatica"
}

###
PUT http://localhost:4001/api/alunos/1
Content-Type: application/json

{
  "nome": "Sofia",
  "idade": 14,
  "curso": "design"
}

###
PUT http://localhost:4001/api/alunos/2
Content-Type: application/json

{
  "nome": "André",
  "idade": 18,
  "curso": "multimédia"
}

###
DELETE http://localhost:4001/api/alunos/1
Content-Type: application/json

###
DELETE http://localhost:4001/api/alunos/1
Content-Type: application/json
cargo: Admin





//daniel