POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name":"ex5",
  "port":4005,
  "protocol":"http",
  "stubs":[
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"campos obrigatórios em falta: nome, cargo e salário"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/funcionarios","method":"POST"}},
        {"or":[
          {"exists":{"body":{"nome": false}}},
          {"exists":{"body":{"cargo": false}}},
          {"exists":{"body":{"salario": false}}}
        ]}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"o salário não pode ser inferior ao salário mínimo (760€)"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/funcionarios","method":"POST"}},
        {"deepEquals":{"body":{"salario":450}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":201,
          "headers":{"Content-Type":"application/json"},
          "body":{
            "mensagem":"funcionário registado com sucesso",
            "id":105,
            "nome":"leonor",
            "cargo":"analista de sistemas",
            "salario":1100
          }
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/funcionarios","method":"POST"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"não é permitido definir salário abaixo de 760€"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/funcionarios/1/salario","method":"PUT"}},
        {"deepEquals":{"body":{"salario":650}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{
            "mensagem":"salário atualizado com sucesso",
            "id":1,
            "novo_salario":1300
          }
        }
      }],
      "predicates":[
        {"equals":{"path": "/api/funcionarios/1/salario","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":409,
          "headers":{"Content-Type": "application/json"},
          "body":{"erro":"não é possível remover o funcionário devido a tarefas pendentes"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/funcionarios/2","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"funcionário removido com sucesso"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/funcionarios/1","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":[
            {"id":1,"nome":"joao","cargo":"coordenador de projetos","salario":1350},
            {"id":2,"nome":"sara","cargo":"designer gráfica","salario":920},
            {"id":3,"nome":"nuno","cargo":"técnico de redes","salario":850}
          ]
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/funcionarios","method":"GET"}}
      ]
    }
  ]
}

###
GET http://localhost:4005/api/funcionarios
Content-Type: application/json

###
POST http://localhost:4005/api/funcionarios
Content-Type: application/json

{
  "nome":"tomas",
  "salario":1100
}

###
POST http://localhost:4005/api/funcionarios
Content-Type: application/json

{
  "nome":"tomas",
  "cargo":"analista",
  "salario":450
}

###
POST http://localhost:4005/api/funcionarios
Content-Type: application/json

{
  "nome":"tomas",
  "cargo":"desenvolvedor",
  "salario":1100
}

###
PUT http://localhost:4005/api/funcionarios/1/salario
Content-Type: application/json

{
  "salario":650
}

###
PUT http://localhost:4005/api/funcionarios/1/salario
Content-Type: application/json

{
  "salario":1300
}

###
DELETE http://localhost:4005/api/funcionarios/2
Content-Type: application/json

###
DELETE http://localhost:4005/api/funcionarios/1
Content-Type: application/json





//daniel