POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name":"ex2",
  "port":4002,
  "protocol":"http",
  "stubs":[
    {
      "responses":[{
        "is": {
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"error":"valor invalido"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos","method":"POST"}},
        {
          "equals":{
            "body":{
              "quantidade":-3
            }
          }
        }
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":201,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"produto adicionado com sucesso","id":3}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos","method":"POST"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":[
            {"id":1,"nome":"Headphones","preco":59.99,"quantidade":8},
            {"id":2,"nome":"webcam descontinuada","preco":29.99,"quantidade":0}
          ]
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type": "application/json"},
          "body":{"id":1,"nome":"headphones","preco":59.99,"quantidade":8}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos/1","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"stock updated","nova_quantidade":12}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos/1/stock","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":404,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"produto inexistente"}
        }
      }],
      "predicates":[
        {"contains":{"path":"/api/produtos/999"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"produto descontinuado removido"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos/2","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"não e possivel remover, produto ainda tem stock disponivel"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos/1","method":"DELETE"}}
      ]
    }
  ]
}

###
GET http://localhost:4002/api/produtos
Content-Type: application/json

###
GET http://localhost:4002/api/produtos/1
Content-Type: application/json

###
POST http://localhost:4002/api/produtos
Content-Type: application/json

{
  "nome":"impressora",
  "preco":199.99,
  "quantidade":-3
}

###
POST http://localhost:4002/api/produtos
Content-Type:application/json

{
  "nome":"impressora",
  "preco":199.99,
  "quantidade":15
}

###
PUT http://localhost:4002/api/produtos/1/stock
Content-Type: application/json

{
  "quantidade":4
}

###
GET http://localhost:4002/api/produtos/999
Content-Type: application/json

###
DELETE http://localhost:4002/api/produtos/1
Content-Type: application/json

###
DELETE http://localhost:4002/api/produtos/2
Content-Type: application/json















//daniel